# Generated by Django 3.2.4 on 2021-08-06 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250, verbose_name='descricao')),
                ('nota', models.IntegerField(blank=True, null=True, verbose_name='nota')),
                ('data_avaliacao', models.CharField(blank=True, max_length=10, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioCliente', to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioProfissional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'testeAvaliacao',
                'db_table': 'testeAvaliacao',
            },
        ),
    ]
