# Generated by Django 3.2.4 on 2021-08-06 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teste', '0002_alter_testeavaliacao_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testeavaliacao',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioProfissional', to=settings.AUTH_USER_MODEL),
        ),
    ]
