# Generated by Django 3.2.4 on 2021-08-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0010_testeavaliacao_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testeavaliacao',
            name='prof',
        ),
    ]
