# Generated by Django 3.2.4 on 2021-08-18 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teste', '0011_remove_testeavaliacao_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='testeavaliacao',
            name='profUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
