# Generated by Django 3.2.4 on 2021-08-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0012_testeavaliacao_profuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testeavaliacao',
            name='profUser',
        ),
    ]
