# Generated by Django 3.2.4 on 2021-07-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20210702_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['id'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='categorias',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='decricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='slogan',
            new_name='imagem',
        ),
    ]
