# Generated by Django 3.2.4 on 2021-07-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20210702_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(blank=True, choices=[('assist', 'Assistencia Tecnica'), ('eventos', 'Eventos'), ('moda', 'Moda'), ('beleza', 'Beleza'), ('reforma', 'Reforma'), ('outros', 'Outros')], max_length=20),
        ),
    ]
