# Generated by Django 3.2.4 on 2021-07-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_remove_categoria_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='descricao',
            field=models.CharField(max_length=250, verbose_name='descricao'),
        ),
    ]
