# Generated by Django 3.2.4 on 2021-07-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_perfil_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rua',
            field=models.CharField(default=1, max_length=60, verbose_name='cidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(max_length=40, verbose_name='cidade'),
        ),
    ]
