# Generated by Django 3.2.4 on 2021-07-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20210702_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.IntegerField(max_length=10, verbose_name='cep'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rua',
            field=models.CharField(max_length=60, verbose_name='rua'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='uf'),
        ),
    ]
