# Generated by Django 3.2.4 on 2021-07-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_alter_perfil_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
    ]
