# Generated by Django 3.2.4 on 2021-07-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Atalho'),
        ),
    ]
