# Generated by Django 3.2.4 on 2021-07-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_perfil_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='first_name',
            field=models.CharField(default=1, max_length=250, verbose_name='first_name '),
            preserve_default=False,
        ),
    ]
