# Generated by Django 3.2.4 on 2021-07-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0018_perfil_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(default=1, max_length=15, verbose_name='telefone'),
            preserve_default=False,
        ),
    ]
