# Generated by Django 3.2.4 on 2021-07-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0019_perfil_telefone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
