# Generated by Django 3.2.4 on 2021-07-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_rename_proficional_avaliacao_profissional'),
        ('usuario', '0021_usuario_imagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='Profissional',
        ),
    ]
