# Generated by Django 3.2.4 on 2021-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_rename_perfil_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='uf',
        ),
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(default=1, max_length=40, verbose_name='bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(default=1, max_length=40, verbose_name='cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rua',
            field=models.CharField(default=1, max_length=60, verbose_name='rua'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default=1, max_length=15, verbose_name='telefone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='uf',
            field=models.CharField(default=1, max_length=2, verbose_name='uf'),
            preserve_default=False,
        ),
    ]
