# Generated by Django 3.2.4 on 2021-07-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0023_auto_20210719_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=0),
        ),
    ]
