# Generated by Django 3.2.4 on 2021-08-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0025_remove_usuario_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'ordering': ['id'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissional'},
        ),
    ]
