# Generated by Django 3.2.4 on 2021-08-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0027_alter_profissional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='avaliado',
            field=models.IntegerField(blank=True, null=True, verbose_name='avaliado'),
        ),
    ]
