# Generated by Django 3.2.4 on 2021-08-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0028_profissional_avaliado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='avaliado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='avaliado',
            field=models.IntegerField(blank=True, null=True, verbose_name='avaliado'),
        ),
    ]
