# Generated by Django 3.2.4 on 2021-08-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0036_rename_usuario_profissional_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='us',
        ),
    ]
