# Generated by Django 3.2.4 on 2021-08-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0037_remove_profissional_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='avaliado',
        ),
    ]
