# Generated by Django 3.2.4 on 2021-08-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0038_remove_usuario_avaliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='descricao',
            field=models.CharField(max_length=250, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='profissao',
            field=models.CharField(max_length=250, verbose_name='Profissão'),
        ),
    ]
