# Generated by Django 3.2.4 on 2021-08-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0039_auto_20210820_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='acesso',
            field=models.BooleanField(default=True),
        ),
    ]
