# Generated by Django 3.2.4 on 2021-08-23 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0040_profissional_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usario', to=settings.AUTH_USER_MODEL),
        ),
    ]
