# Generated by Django 3.2.4 on 2021-08-23 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0042_alter_profissional_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='user',
            field=models.ForeignKey(error_messages={'unique': 'Já existe um profissional cadastrado para este usuário.'}, on_delete=django.db.models.deletion.CASCADE, related_name='usario', to=settings.AUTH_USER_MODEL),
        ),
    ]
