# Generated by Django 3.2.4 on 2021-08-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0044_alter_profissional_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='acesso',
            new_name='acesso_permitido',
        ),
    ]
