# Generated by Django 3.2.4 on 2021-08-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0046_remove_categoria_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='nome',
            field=models.CharField(blank=True, choices=[('assist', 'Assistencia Tecnica'), ('eventos', 'Eventos'), ('moda', 'Moda'), ('beleza', 'Beleza'), ('reforma', 'Reforma'), ('outros', 'Outros')], max_length=20),
        ),
    ]
