# Generated by Django 3.2.4 on 2021-08-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0047_profissional_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='categoria',
        ),
        migrations.AddField(
            model_name='profissional',
            name='categoria',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='usuario.categoria'),
            preserve_default=False,
        ),
    ]
