# Generated by Django 3.2.4 on 2021-08-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0048_auto_20210824_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='categoria',
        ),
        migrations.AddField(
            model_name='profissional',
            name='categoria',
            field=models.ManyToManyField(to='usuario.Categoria'),
        ),
    ]
