# Generated by Django 3.2.4 on 2021-08-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0051_alter_categoria_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(blank=True, choices=[('Assistência técnica', 'Assistência técnica'), ('Aulas', 'Aulas'), ('Consultorias', 'Consultorias'), ('Design e tecnologia', 'Design e tecnologia'), ('Eventos', 'Eventos'), ('Moda', 'Moda'), ('Beleza', 'Beleza'), ('Reformas e reparos', 'Reforma'), ('Saúde', 'Saúde'), ('Serviços Domésticos', 'Serviços Domésticos'), ('Outros', 'Outros')], max_length=20),
        ),
    ]
