# Generated by Django 3.2.4 on 2021-08-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0052_alter_categoria_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_profissional',
            field=models.BooleanField(default=False),
        ),
    ]
