# Generated by Django 3.2.4 on 2021-08-26 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0054_alter_profissional_acesso_permitido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='acesso_permitido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_profissional',
        ),
    ]
