# Generated by Django 3.2.4 on 2021-08-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0056_usuario_is_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='acesso_permitido',
            field=models.BooleanField(default=False),
        ),
    ]
