# Generated by Django 3.2.4 on 2021-08-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0057_profissional_acesso_permitido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='acesso_permitido',
            field=models.BooleanField(default=True),
        ),
    ]
