# Generated by Django 3.2.4 on 2021-09-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0058_alter_profissional_acesso_permitido'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
