# Generated by Django 3.2.4 on 2021-09-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0059_profissional_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
