# Generated by Django 3.2.4 on 2021-09-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0060_alter_profissional_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='cpf',
        ),
    ]
