# Generated by Django 3.2.4 on 2021-10-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0062_profissional_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='cpf',
        ),
    ]
