# Generated by Django 3.2.4 on 2021-11-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0064_auto_20211022_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='imagem',
            field=models.ImageField(default=1, upload_to='fotos/%Y/%m/'),
            preserve_default=False,
        ),
    ]
