# Generated by Django 3.2.4 on 2021-07-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='proficional',
            new_name='profissional',
        ),
    ]
