# Generated by Django 3.2.4 on 2021-08-06 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0025_remove_usuario_status'),
        ('avaliacao', '0003_alter_avaliacao_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to='usuario.profissional'),
        ),
    ]
