# Generated by Django 3.2.4 on 2021-08-13 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_alter_avaliacao_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='data_avaliacao',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Avaliação'),
        ),
    ]
