# Generated by Django 3.2.4 on 2021-08-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0007_auto_20210817_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='prof',
        ),
    ]
