# Generated by Django 3.2.4 on 2021-08-17 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0034_alter_profissional_user'),
        ('avaliacao', '0008_remove_avaliacao_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to='usuario.profissional'),
        ),
    ]
