# Generated by Django 3.2.4 on 2021-08-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0009_avaliacao_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='data_avaliacao',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='profissional',
        ),
    ]
