# Generated by Django 3.2.4 on 2021-08-17 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0034_alter_profissional_user'),
        ('avaliacao', '0010_auto_20210817_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='descricao',
            field=models.CharField(default=-1, max_length=250, verbose_name='descricao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(blank=True, null=True, verbose_name='nota'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to='usuario.profissional'),
        ),
    ]
