# Generated by Django 3.2.4 on 2021-10-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0013_auto_20210914_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='data_avaliacao',
        ),
    ]
