# Generated by Django 3.2.4 on 2021-10-22 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0014_remove_avaliacao_data_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
