# Generated by Django 3.2.4 on 2021-11-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0015_avaliacao_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
