# Generated by Django 3.2.4 on 2021-11-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0016_alter_avaliacao_data_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='media',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='soma',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='total_pessoas',
        ),
    ]
