# Generated by Django 3.2.4 on 2021-11-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0017_auto_20211122_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='descricao'),
        ),
    ]
