# Generated by Django 3.2.4 on 2021-08-16 23:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mensagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_notificacao', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Data Notificação')),
                ('texto', models.CharField(max_length=255, null=True)),
                ('mensagemRecebida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagemRecebida', to='mensagem.mensagem')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'Notificacao',
            },
        ),
    ]
