# Generated by Django 3.2.4 on 2021-07-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mensagem',
            table='Mensagen',
        ),
    ]
