# Generated by Django 3.2.4 on 2021-07-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0002_alter_mensagem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='nomeRemetente',
            field=models.CharField(default=1, max_length=100, verbose_name='nomeRemetente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='destinatario',
            field=models.IntegerField(blank=True, null=True, verbose_name='destinatario'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='remetente',
            field=models.IntegerField(blank=True, null=True, verbose_name='remetente'),
        ),
    ]
