# Generated by Django 3.2.4 on 2021-07-12 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensagem', '0003_auto_20210712_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='nomeRemetente',
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to=settings.AUTH_USER_MODEL),
        ),
    ]
