# Generated by Django 3.2.4 on 2021-08-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0004_auto_20210712_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='data_mensagem',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
